-- 코드를 입력하세요
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO as a, 
(SELECT c.FOOD_TYPE, MAX(c.FAVORITES) as FAVORITES
FROM REST_INFO as c
GROUP BY c.FOOD_TYPE) as b
WHERE a.FOOD_TYPE = b.FOOD_TYPE and a.FAVORITES = b.FAVORITES
ORDER BY a.FOOD_TYPE DESC