-- 코드를 입력하세요
SELECT C.MEMBER_NAME, D.REVIEW_TEXT, left(D.REVIEW_DATE,10) as REVIEW_DATE
FROM (SELECT b.MEMBER_ID FROM REST_REVIEW as b GROUP BY b.MEMBER_ID ORDER BY COUNT(b.MEMBER_ID)  DESC LIMIT 1 ) as a
, MEMBER_PROFILE as c
INNER JOIN REST_REVIEW as d
ON c.MEMBER_ID = d.MEMBER_ID
WHERE C.MEMBER_ID  = a.MEMBER_ID
ORDER BY D.REVIEW_DATE, D.REVIEW_TEXT