-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE as PRODUCT_CODE, SUM(SALES_AMOUNT*PRODUCT.PRICE) as SALES
FROM PRODUCT RIGHT JOIN OFFLINE_SALE
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC