-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, LEFT(START_DATE, 10) as START_DATE , LEFT(END_DATE, 10) as END_DATE, 
CASE
WHEN datediff(END_DATE, START_DATE) >= 29 THEN "장기 대여"
ELSE "단기 대여" END as "RENT_TYPE"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) = 9
ORDER BY HISTORY_ID DESC