words = input()
words =words.replace("c=", "1")
words =words.replace("c-", "2")
words =words.replace("dz=", "3")
words =words.replace("d-", "4")
words =words.replace("lj", "5")
words =words.replace("nj", "6")
words =words.replace("s=", "7")
words =words.replace("z=", "8")
print(len(words))