-- 코드를 입력하세요
SELECT MCDP_CD as "진료과코드", COUNT(MCDP_CD) as "5월예약건수"
FROM APPOINTMENT
WHERE APNT_YMD like '%2022-05%'#MONTH(APNT_YMD) = "05" AND YEAR(APNT_YMD) = "2022"
GROUP BY MCDP_CD
ORDER BY COUNT(MCDP_CD) ASC, MCDP_CD ASC